// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWoThk2vIUxe0YUiRhpBe_lb0uKhA9X00',
    appId: '1:81467142268:web:c439c626688073fab899f9',
    messagingSenderId: '81467142268',
    projectId: 'campusx-5d0c3',
    authDomain: 'campusx-5d0c3.firebaseapp.com',
    storageBucket: 'campusx-5d0c3.firebasestorage.app',
    measurementId: 'G-K1N534T162',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa1SkhTzztxM3vvcP1N6HEKxXIdK4P-oU',
    appId: '1:81467142268:android:1443d6dd8b17df69b899f9',
    messagingSenderId: '81467142268',
    projectId: 'campusx-5d0c3',
    storageBucket: 'campusx-5d0c3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWoThk2vIUxe0YUiRhpBe_lb0uKhA9X00',
    appId: '1:81467142268:web:57a9a0d677a8883eb899f9',
    messagingSenderId: '81467142268',
    projectId: 'campusx-5d0c3',
    authDomain: 'campusx-5d0c3.firebaseapp.com',
    storageBucket: 'campusx-5d0c3.firebasestorage.app',
    measurementId: 'G-37CP1929D9',
  );

}